/**
 * Attendance Review exports (PR-3): Excel workbook + Word action pack, built from a STORED run result.
 * Pure functions of the run (no DB reads) so the file always matches what the admin reviewed/finalised.
 * Contains names and indicative ₹ → served to admin only (the router enforces it).
 */
const XLSX = require('xlsx');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell, WidthType, AlignmentType,
  PageOrientation, ShadingType, BorderStyle, PageBreak, Footer, PageNumber,
} = require('docx');

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const MON3 = MONTHS.map((m) => m.slice(0, 3).toUpperCase());
const inr = (n) => `₹${Math.round(Number(n) || 0).toLocaleString('en-IN')}`;
const days = (d) => (d === 1 ? '1 day' : `${d} days`);
const hm = (min) => { const m = Math.round(Number(min) || 0); return m >= 60 ? `${Math.floor(m / 60)} h${m % 60 ? ` ${m % 60} min` : ''}` : `${m} min`; };
const people = (n) => (n === 1 ? '1 person' : `${n} people`);
// Names in the master sometimes carry trailing digits or doubled spaces; notes and notices show them clean.
const cleanName = (n) => String(n || '').replace(/[\d\s]+$/, '').replace(/\s+/g, ' ').trim();
const fmtDay = (iso) => { const d = new Date(`${iso}T00:00:00Z`); return `${d.getUTCDate()} ${MONTHS[d.getUTCMonth()].slice(0, 3)}`; };
function todayIst(now = new Date()) {
  return now.toLocaleDateString('en-IN', { timeZone: 'Asia/Kolkata', day: 'numeric', month: 'long', year: 'numeric' });
}
function monthLabel(result) { const { month, year } = result.meta; return `${MONTHS[month - 1]} ${year}`; }
function prevLabel(result) { const [y, m] = result.meta.prev_ym.split('-').map(Number); return `${MONTHS[m - 1]} ${y}`; }
const fileStem = (result) => `${MONTHS[result.meta.month - 1].slice(0, 3)}${result.meta.year}`;

// ── Excel ────────────────────────────────────────────────────────────────

function sheet(rows, cols) {
  const aoa = [cols.map((c) => c.h), ...rows.map((r) => cols.map((c) => { const v = c.v ? c.v(r) : r[c.k]; return v === undefined || v === null ? '' : v; }))];
  const ws = XLSX.utils.aoa_to_sheet(aoa);
  ws['!cols'] = cols.map((c) => ({ wch: c.w || Math.max(10, c.h.length + 2) }));
  ws['!autofilter'] = { ref: XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: Math.max(aoa.length - 1, 0), c: cols.length - 1 } }) };
  return ws;
}

function buildWorkbook(result, run = {}) {
  const wb = XLSX.utils.book_new();
  const m = result.meta; const t = result.actionTotals || {}; const mon = result.trend?.monthly || {};
  const g = (ym, grp, k) => mon[ym]?.[grp]?.[k] ?? '';
  const summary = [
    ['Attendance Review', monthLabel(result)],
    ['Status', run.status ? String(run.status).toUpperCase() : 'PREVIEW'],
    ['Generated by', run.generated_by || ''], ['Generated at (UTC)', run.generated_at || ''],
    ['Finalised by', run.finalised_by || ''], ['Finalised at (UTC)', run.finalised_at || ''],
    [],
    ['People assessed', m.people_assessed], ['Excluded by config', m.excluded_people],
    ['Action list', t.people], ['Deduction notes', t.deduction_notes], ['Warning notes', t.warning_notes],
    ['Deduction days', t.deduction_days], ['Indicative amount (₹, payroll decides)', t.indicative_amount],
    ['Early-exit warnings', (result.earlyExitWarnings || []).length],
    ['Late notice names', (result.noticeLate || []).length], ['Early notice names', (result.noticeEarly || []).length],
    ['Release days (not counted)', (m.release_days || []).join(', ')],
    ['Gate passes recorded', result.gatePassCount],
    [],
    ['Group', `Late % ${m.prev_ym}`, `Late % ${m.ym}`, `Early % ${m.prev_ym}`, `Early % ${m.ym}`, `Time lost % ${m.ym}`],
    ...['Company', 'Contract', 'All'].map((grp) => [grp, g(m.prev_ym, grp, 'late_pct'), g(m.ym, grp, 'late_pct'), g(m.prev_ym, grp, 'early_pct'), g(m.ym, grp, 'early_pct'), g(m.ym, grp, 'time_lost_pct')]),
  ];
  const ws = XLSX.utils.aoa_to_sheet(summary); ws['!cols'] = [{ wch: 38 }, { wch: 16 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, ws, 'Summary');

  const cats = (r) => (r.categories || []).join(', ');
  XLSX.utils.book_append_sheet(wb, sheet(result.actionList || [], [
    { k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'designation', h: 'Designation', w: 20 },
    { k: 'group', h: 'Group' }, { k: 'worked_days', h: 'Worked days' }, { k: 'late_days', h: 'Late days' }, { k: 'early_days', h: 'Early exits' },
    { k: 'late_min', h: 'Late min' }, { k: 'early_min', h: 'Early min' }, { k: 'shift_h', h: 'Shift h' }, { k: 'workdays_lost', h: 'Workdays lost' },
    { k: 'lm_late', h: 'Last month late', v: (r) => r.last_month?.late_days ?? 'new' }, { k: 'lm_early', h: 'Last month early', v: (r) => r.last_month?.early_days ?? 'new' },
    { k: 'categories', h: 'Why', v: cats, w: 30 }, { k: 'action', h: 'Action' }, { k: 'deduction_days', h: 'Deduction days' },
    { k: 'indicative_amount', h: 'Indicative ₹' }, { k: 'override', h: 'Override', v: (r) => (r.override ? `${r.override.action}: ${r.override.reason}` : ''), w: 30 },
    { k: 'shift', h: 'Shift check', v: (r) => (r.check_master_shift ? 'check master shift' : ''), w: 20 },
  ]), 'Action list');
  XLSX.utils.book_append_sheet(wb, sheet(result.earlyExitWarnings || [], [
    { k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'early_exits', h: 'Early exits' },
    { k: 'over_1h', h: '1 h or more' }, { k: 'early_min', h: 'Early min' }, { k: 'option_c_days', h: 'Option C days' }, { k: 'action', h: 'Action' }, { k: 'deduction_days', h: 'Deduction days' },
  ]), 'Early-exit warnings');
  XLSX.utils.book_append_sheet(wb, sheet(result.noticeLate || [], [{ k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'late_days', h: 'Late days' }]), 'Notice late');
  XLSX.utils.book_append_sheet(wb, sheet(result.noticeEarly || [], [{ k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'early_exits', h: 'Early exits' }]), 'Notice early');
  XLSX.utils.book_append_sheet(wb, sheet(result.departments || [], [
    { k: 'department', h: 'Department', w: 20 }, { k: 'people', h: 'People' }, { k: 'worked_days', h: 'Worked days' }, { k: 'late_days', h: 'Late days' },
    { k: 'early_exits', h: 'Early exits' }, { k: 'late_min', h: 'Late min' }, { k: 'early_min', h: 'Early min' }, { k: 'sched_min', h: 'Scheduled min' },
    { k: 'workdays_lost', h: 'Workdays lost' }, { k: 'time_lost_pct', h: 'Time lost %' },
  ]), 'By department');
  XLSX.utils.book_append_sheet(wb, sheet(result.people || [], [
    { k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'group', h: 'Group' },
    { k: 'worked_days', h: 'Worked days' }, { k: 'late_days', h: 'Late days' }, { k: 'early_days', h: 'Early exits' }, { k: 'late_min', h: 'Late min' },
    { k: 'early_min', h: 'Early min' }, { k: 'workdays_lost', h: 'Workdays lost' }, { k: 'newcomer', h: 'Newcomer', v: (r) => (r.newcomer ? 'yes' : '') },
    { k: 'remeasured', h: 'Re-measured', v: (r) => (r.remeasured ? 'yes' : '') }, { k: 'hours_excused', h: 'Re-measured: excused (full hours)', v: (r) => r.hours_excused || '' }, { k: 'late_full_excused', h: 'Lates not counted (full hours)', v: (r) => r.late_full_excused || '' }, { k: 'categories', h: 'Why selected', v: cats, w: 30 },
  ]), 'All with late or early');
  XLSX.utils.book_append_sheet(wb, sheet(result.shiftIssues || [], [
    { k: 'code', h: 'Code' }, { k: 'department', h: 'Department', w: 18 }, { k: 'master_shift', h: 'Master shift', w: 16 }, { k: 'used_shift', h: 'Shift used', w: 16 },
    { k: 'days', h: 'Days' }, { k: 'min_in', h: 'Min in' }, { k: 'max_in', h: 'Max in' }, { k: 'min_out', h: 'Min out' }, { k: 'max_out', h: 'Max out' }, { k: 'late', h: 'Late' }, { k: 'early', h: 'Early' },
  ]), 'Shift issues');
  XLSX.utils.book_append_sheet(wb, sheet(result.shiftCheck || [], [
    { k: 'code', h: 'Code' }, { k: 'name', h: 'Name', w: 26 }, { k: 'department', h: 'Department', w: 18 }, { k: 'shift_h', h: 'Shift h' },
    { k: 'ms_days', h: 'Worked (Mon–Sat)' }, { k: 'system_early', h: 'System early exits' }, { k: 'excused', h: 'Full hours – not counted' },
    { k: 'counted', h: 'Counted' }, { k: 'avg_hours', h: 'Avg hours those days' },
    { k: 'result', h: 'Result', w: 30, v: (r) => (r.check_master ? 'Check master shift' : { hidden: 'Not shown – full hours worked', shown: 'Shown – short of shift hours', below_threshold: 'Below warning threshold' }[r.result]) },
  ]), 'Shift check');
  XLSX.utils.book_append_sheet(wb, sheet(result.payrollChecks?.flags || [], [
    { k: 'code', h: 'Code' }, { k: 'flag', h: 'Problem', w: 32 }, { k: 'rows', h: 'Rows' }, { k: 'daycalc_days', h: 'Day-calc days' }, { k: 'salary_amount', h: 'Salary deduction ₹' },
  ]), 'Payroll checks');
  const crit = Object.entries(result.criteria?.thresholds || {}).map(([k, v]) => [k, v]);
  const cs = XLSX.utils.aoa_to_sheet([['Rule', 'Value'], ['stayed_late_mode', result.criteria?.stayed_late_mode], ['early_exit_rule', result.criteria?.early_exit_rule], ['shift_fit', result.criteria?.shift_fit ?? ''], ['late_full_hours', result.criteria?.late_full_hours === false ? 'off' : 'on'],
    ['loading_designation_patterns', (result.criteria?.loading_designation_patterns || []).join(', ')], ...crit,
    ...Object.entries(result.criteria?.remeasure || {}).map(([code, r]) => [`re-measure ${code}`,
      `${r.start}–${r.end}, late grace ${r.late_grace ?? 9} min, early grace ${r.early_grace ?? 15} min, stayed-late ${r.left_late || 'system'}`
      + (r.hours_complete ? `, full shift hours excuse a late or early exit (tolerance ${r.hours_grace ?? 10} min)` : '')]),
    ...(result.overridesApplied || []).map((o) => [`override ${o.code}`, `${o.action}: ${o.reason} → ${o.effect}`])]);
  cs['!cols'] = [{ wch: 30 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, cs, 'Rules used');
  return XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
}

// ── Word ─────────────────────────────────────────────────────────────────

const F = 'Arial';
const tr = (s, o = {}) => new TextRun({ text: String(s), font: F, size: o.size || 21, bold: o.bold, italics: o.it, color: o.color });
const para = (runs, o = {}) => new Paragraph({ children: Array.isArray(runs) ? runs : [tr(runs, o)], alignment: o.align, spacing: { after: o.after ?? 120, before: o.before ?? 0 } });
const BORDER = { style: BorderStyle.SINGLE, size: 4, color: 'BFBFBF' };
const NONE = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
const cell = (s, w, o = {}) => new TableCell({
  width: { size: w, type: WidthType.DXA }, shading: o.fill ? { type: ShadingType.CLEAR, fill: o.fill, color: 'auto' } : undefined,
  margins: { top: o.tight ? 15 : 40, bottom: o.tight ? 15 : 40, left: 70, right: 70 }, borders: { top: BORDER, bottom: BORDER, left: BORDER, right: BORDER },
  children: [new Paragraph({ alignment: o.align, children: [tr(s, { size: o.size || 17, bold: o.bold, color: o.color })] })],
});
function table(heads, rows, widths, size, tight) {
  return new Table({
    width: { size: widths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: widths,
    rows: [
      new TableRow({ tableHeader: true, children: heads.map((h, i) => cell(h, widths[i], { bold: true, fill: '1F3864', color: 'FFFFFF', size, tight })) }),
      ...rows.map((r) => new TableRow({ cantSplit: true, children: r.map((v, i) => cell(v?.v ?? v ?? '', widths[i], { fill: v?.fill, align: v?.align, bold: v?.bold, size, tight })) })),
    ],
  });
}
const C = AlignmentType.CENTER; const R = AlignmentType.RIGHT;

function signature() {
  const side = (txt, align) => new TableCell({ width: { size: 4500, type: WidthType.DXA }, borders: { top: NONE, bottom: NONE, left: NONE, right: NONE },
    children: [para('______________________', { after: 40, align }), para([tr(txt, { bold: true })], { after: 0, align })] });
  return [para('', { after: 500 }), new Table({ width: { size: 9000, type: WidthType.DXA }, columnWidths: [4500, 4500],
    rows: [new TableRow({ children: [side('HR Manager'), side('Received by employee (signature & date)', R)] })] })];
}

function buildDocx(result, run = {}, { now = new Date() } = {}) {
  const ML = monthLabel(result); const PL = prevLabel(result); const today = todayIst(now);
  const draft = run.status !== 'final';
  const ref = (i) => `HR/ATT/${MON3[result.meta.month - 1]}${String(result.meta.year).slice(2)}/${String(i + 1).padStart(2, '0')}`;
  const optionC = result.criteria?.early_exit_rule === 'option_c';
  const rel = (result.meta.release_days || []).map(fmtDay);
  const relText = rel.length ? `Plant-wide early-release days (${rel.join(', ')}) are not counted.` : '';
  const list = result.actionList || []; const ew = result.earlyExitWarnings || [];
  const ded = list.filter((a) => a.action === 'deduction'); const warn = list.filter((a) => a.action !== 'deduction');
  const chk = list.filter((a) => a.check_master_shift);
  const tot = result.actionTotals || {};
  const t = result.criteria?.thresholds || {};
  const fullLate = result.criteria?.late_full_hours !== false; const fullEarly = result.criteria?.shift_fit === 'everyone';
  const fullText = fullLate && fullEarly ? 'A late arrival or early exit is not counted on a day you still worked your full shift hours.'
    : fullLate ? 'A late arrival is not counted on a day you still worked your full shift hours.' : '';
  const copyTo = (p) => (p.group === 'Contract' ? [para([tr(`Copy to: ${p.department || ''} contractor`, { size: 19, it: true })], { before: 120 })] : []);
  const draftMark = draft ? [para([tr('DRAFT — not finalised. Do not issue.', { bold: true, color: 'C00000', size: 20 })], { after: 80 })] : [];

  // Section 1 — action list (landscape, HR + finance only: carries ₹)
  const s1 = [
    ...draftMark,
    para([tr(`Late Coming & Early Exit – Action List, ${ML}`, { size: 30, bold: true })], { after: 60 }),
    para([tr(`Prepared ${today} · HR Department · For HR and Finance only – not for display`, { size: 18, color: '595959' })], { after: 160 }),
    para([tr(`${people(list.length)}: ${ded.length} ${ded.length === 1 ? 'gets' : 'get'} a deduction note (${days(tot.deduction_days || 0)} in total, about ${inr(tot.indicative_amount)}), ${warn.length} ${warn.length === 1 ? 'gets' : 'get'} a warning note.${chk.length ? ` ${people(chk.length)} flagged "check master shift" – confirm the shift before issuing.` : ''}`, { size: 21 })], { after: 80 }),
    para([tr(`Deduction = workdays actually lost (late minutes + early-exit minutes ÷ shift length), rounded to the nearest ${t.rounding_step ?? 0.5} day, minimum ${t.min_deduction ?? 0.5} day. Mornings after the person stayed late the previous evening are not counted.${fullLate ? ` Nor are lates${fullEarly ? ' or early exits' : ''} on days the full shift was still worked.` : ''} ${relText} ₹ amounts are indicative (monthly gross ÷ days in month × days); payroll gives the final figure.`, { size: 18, color: '404040' })], { after: 120 }),
    table(['#', 'Code', 'Name', 'Department – Role', 'Late days', 'Early days', 'Time lost', 'Workdays lost', 'Action', 'Deduction', 'Indicative ₹', 'Remark'],
      list.map((p, i) => [{ v: i + 1, align: C }, { v: p.code, align: C }, { v: cleanName(p.name), bold: true }, `${p.department || ''} – ${p.designation || ''}`,
        { v: p.late_days, align: C }, { v: p.early_days, align: C }, hm(p.late_min + p.early_min), { v: Number(p.workdays_lost).toFixed(2), align: C },
        { v: p.action === 'deduction' ? 'Deduction note' : (p.newcomer ? 'Warning note (newcomer)' : 'Warning note'), fill: p.action === 'deduction' ? 'FCE4D6' : 'FFF2CC' },
        { v: p.deduction_days ? days(p.deduction_days) : '—', align: C, bold: true }, { v: p.indicative_amount ? inr(p.indicative_amount) : '—', align: R },
        p.override ? `Override: ${p.override.reason}` : p.check_master_shift ? 'Check master shift: leaves early almost daily, short of shift hours' : (p.remeasured ? `Re-measured on the master shift${p.hours_excused ? `; ${days(p.hours_excused)} not counted (full shift hours worked)` : ''}` : '')])
        .concat([['', '', { v: 'TOTAL', bold: true }, '', '', '', '', '', '', { v: days(tot.deduction_days || 0), align: C, bold: true }, { v: inr(tot.indicative_amount), align: R, bold: true }, '']]),
      [380, 680, 1750, 2750, 600, 600, 1150, 950, 1300, 950, 1050, 3450], 15, true),
    para([tr(`Early-exit ${optionC ? 'deductions and warnings' : 'warning notes'} (${people(ew.length)})`, { size: 24, bold: true })], { before: 240, after: 60 }),
    para([tr(`People who left more than ${t.early_min_exclusive ?? 15} minutes before shift end on ${t.early_warning_min ?? 3} or more days (Mon–Sat), who do not already have a note above. ${optionC ? 'Option C applies: ½ day per exit of 1 hour or more, plus ½ day per 3 shorter exits.' : 'Warning only.'} ${relText}`, { size: 18, color: '404040' })], { after: 100 }),
    table(['#', 'Code', 'Name', 'Department – Role', 'Early exits', '1 h+ early', 'Time', 'Action'],
      ew.map((x, i) => [{ v: i + 1, align: C }, { v: x.code, align: C }, { v: cleanName(x.name), bold: true }, `${x.department || ''} – ${x.designation || ''}`,
        { v: x.early_exits, align: C }, { v: x.over_1h, align: C }, hm(x.early_min),
        { v: x.action === 'deduction' ? `Deduction ${days(x.deduction_days)}` : 'Warning note', fill: x.action === 'deduction' ? 'FCE4D6' : 'FFF2CC' }]),
      [400, 700, 2200, 3600, 1000, 1000, 1300, 1600], 15, true),
  ];

  // Section 2 — notice board (no money, no minutes)
  const noticeHead = (title, intro, points) => [
    para([tr('NOTICE', { size: 32, bold: true })], { align: C, after: 20 }),
    para([tr(`${title} – ${ML}`, { size: 26, bold: true })], { align: C, after: 120 }),
    para(intro, { size: 19, after: 60 }),
    ...points.map((pt, i) => para(`${i + 1}.  ${pt}`, { size: 18, after: 20 })),
    para('', { after: 60 }),
  ];
  const sign = [para([tr(`Date: ${today}`, { size: 20 }), tr('                                                                        HR Manager', { size: 20, bold: true })], { before: 60, after: 0 })];
  const s2 = [
    ...noticeHead('Late Coming', `The following employees came late to duty on ${t.notice_late ?? 4} or more days in ${ML}.`, [
      `Reporting ${t.late_min_minutes ?? 10} minutes or more after shift start is marked as late.`,
      'A late morning is not counted if you stayed late after your shift the previous evening.',
      ...(fullText ? [fullText] : []),
      'Time lost by late coming and early leaving is deducted from salary, in half-day steps.',
      'Leaving before shift end without a gate pass or approved short leave is treated the same as late coming.',
    ]),
    table(['S.No', 'Code', 'Name', 'Department', 'Late days'], (result.noticeLate || []).map((n, i) => [{ v: i + 1, align: C }, { v: n.code, align: C }, cleanName(n.name), n.department || '', { v: n.late_days, align: C, bold: true }]), [600, 900, 3300, 2900, 1300], 16, true),
    para('Anyone who believes their record is wrong should meet HR within 3 working days with the reason.', { size: 17, before: 60, after: 0 }),
    ...sign,
    new Paragraph({ children: [new PageBreak()] }),
    ...noticeHead('Leaving Early', `The following employees left before the end of their shift on ${t.notice_early ?? 3} or more days in ${ML} without a recorded gate pass or short leave.`, [
      `Leaving more than ${t.early_min_exclusive ?? 15} minutes before shift end without a gate pass or approved short leave is marked as an early exit.`,
      optionC ? 'Early exits are deducted from salary in half-day steps.' : 'Repeated early exits will lead to deduction from salary as per company policy.',
      'If you must leave early, take a gate pass from your in-charge and show it at the gate.',
    ]),
    table(['S.No', 'Code', 'Name', 'Department', 'Early exits'], (result.noticeEarly || []).map((n, i) => [{ v: i + 1, align: C }, { v: n.code, align: C }, cleanName(n.name), n.department || '', { v: n.early_exits, align: C, bold: true }]), [600, 900, 3300, 2900, 1300], 16, true),
    para(`${relText} Anyone who believes their record is wrong should meet HR within 3 working days.`.trim(), { size: 17, before: 60, after: 0 }),
    ...sign,
  ];

  // Section 3 — one note per person
  const head = (p, i, subj) => [
    ...draftMark,
    para([tr('HR Department', { size: 20, bold: true, color: '1F3864' })], { after: 0 }),
    para([tr(`Ref: ${ref(i)}`, { size: 19, color: '595959' }), tr(`          Date: ${today}`, { size: 19, color: '595959' })], { after: 240 }),
    para([tr('To: ', { bold: true }), tr(`${cleanName(p.name)}  (Code ${p.code})`)], { after: 40 }),
    para([tr('Department / Role: ', { bold: true }), tr(`${p.department || ''} – ${p.designation || ''}`)], { after: 200 }),
    para([tr('Subject: ', { bold: true }), tr(subj, { bold: true })], { after: 200 }),
  ];
  const facts = (p) => table(['Month', 'Late days', 'Early-exit days', 'Time lost'], [
    [ML, { v: p.late_days, align: C }, { v: p.early_days, align: C }, `${hm(p.late_min + p.early_min)} (= ${Number(p.workdays_lost).toFixed(2)} workdays)`],
    [PL, { v: p.last_month?.late_days ?? '—', align: C }, { v: p.last_month?.early_days ?? '—', align: C }, '—'],
  ], [2400, 1600, 1900, 3100], 20);
  const notes = [];
  list.forEach((p, i) => {
    if (i > 0) notes.push(new Paragraph({ children: [new PageBreak()] }));
    const what = [p.late_days ? `came late on ${p.late_days} day${p.late_days > 1 ? 's' : ''}` : null, p.early_days ? `left before shift end on ${p.early_days} day${p.early_days > 1 ? 's' : ''}` : null].filter(Boolean).join(' and ') || 'lost working time';
    if (p.action !== 'deduction') {
      notes.push(...head(p, i, `Warning – late coming / early leaving, ${ML}`),
        para(`Our attendance record shows that in ${ML} you ${what}. This is ${hm(p.late_min + p.early_min)} of working time.`), facts(p),
        para(p.newcomer ? 'As you have joined recently, no deduction is being made this month. Please treat this note as a first warning.' : 'No deduction is being made this month. Please treat this note as a warning.', { before: 200 }),
        para(`Any further time lost through late coming or leaving early will be deducted from your salary in half-day steps, as per company policy. A late morning is not counted if you stayed late after your shift the previous evening.${fullText ? ` ${fullText}` : ''}`),
        para('If you need to leave early for a genuine reason, take a gate pass or approved short leave from your in-charge before leaving.'),
        ...copyTo(p), ...signature());
    } else {
      notes.push(...head(p, i, `Late coming / early leaving, ${ML} – deduction of ${days(p.deduction_days)}`),
        para(`Our attendance record shows that in ${ML} you ${what}. Together this is ${hm(p.late_min + p.early_min)} of working time, equal to ${Number(p.workdays_lost).toFixed(2)} workdays.`), facts(p),
        para([tr('As per company attendance policy, a deduction of '), tr(days(p.deduction_days), { bold: true }), tr(' will be made from your salary. Deductions are made in half-day steps, with a minimum of half a day.')], { before: 200 }),
        para(`Late mornings that followed an evening when you stayed late after your shift have not been counted.${fullText ? ` Days on which you still worked your full shift hours have not been counted either.` : ''}`),
        para('Further late coming or leaving early will lead to deductions every month and may lead to stricter action. If you believe this record is wrong, meet HR within 3 working days with the reason or proof.'),
        ...copyTo(p), ...signature());
    }
  });
  ew.forEach((x, j) => {
    const i = list.length + j;
    if (i > 0) notes.push(new Paragraph({ children: [new PageBreak()] }));
    const avg = x.early_exits ? Math.round(x.early_min / x.early_exits) : 0;
    notes.push(...head(x, i, `${x.action === 'deduction' ? 'Deduction' : 'Warning'} – leaving before shift end, ${ML}`),
      para(`Our attendance record shows that in ${ML} you left before the end of your shift on ${x.early_exits} days, with no gate pass or short leave recorded. On average you left ${hm(avg)} early${x.over_1h ? `, and on ${x.over_1h} of these days one hour or more early` : ''}.`),
      table(['Month', 'Early-exit days', 'Total time'], [[ML, { v: x.early_exits, align: C }, hm(x.early_min)]], [3000, 2500, 3500], 20),
      x.action === 'deduction'
        ? para([tr('As per company attendance policy, a deduction of '), tr(days(x.deduction_days), { bold: true }), tr(' will be made from your salary.')], { before: 200 })
        : para(x.newcomer ? 'As you have joined recently, this note is a first warning. No deduction is being made.' : 'This note is a warning. No deduction is being made this month.', { before: 200 }),
      para('Leaving before shift end without a gate pass or approved short leave is treated the same as late coming and is deducted from salary in half-day steps, as per company policy.'),
      para('If you need to leave early for a genuine reason, take a gate pass from your in-charge before leaving and show it at the gate.'),
      ...copyTo(x), ...signature());
  });
  if (!notes.length) notes.push(para(`No individual notes for ${ML}.`));

  const A4 = { width: 11906, height: 16838 };
  const pageFoot = new Footer({ children: [new Paragraph({ alignment: C, children: [new TextRun({ font: F, size: 16, color: '808080', children: ['Page ', PageNumber.CURRENT] })] })] });
  const blankFoot = new Footer({ children: [new Paragraph({ children: [] })] });
  const doc = new Document({
    creator: 'HR Salary System', title: `Late & Early Action Notes – ${ML}`,
    sections: [
      { properties: { page: { size: { ...A4, orientation: PageOrientation.LANDSCAPE }, margin: { top: 500, bottom: 500, left: 600, right: 600 } } }, footers: { default: pageFoot }, children: s1 },
      { properties: { page: { size: A4, margin: { top: 500, bottom: 400, left: 1000, right: 1000 } } }, footers: { default: blankFoot }, children: s2 },
      { properties: { page: { size: A4, margin: { top: 1200, bottom: 1200, left: 1300, right: 1300 } } }, footers: { default: blankFoot }, children: notes },
    ],
  });
  return Packer.toBuffer(doc);
}

module.exports = { buildWorkbook, buildDocx, fileStem, cleanName, todayIst };
